server:
  port: 8010
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
spring:
  application:
    name: nuls-switch
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nuls_switch?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    initialSize: 1
    minIdle: 3
    maxActive: 20
    continue-on-error: true
    # schema: classpath:db/nuls_switch_init.sql
    initialization-mode: always
  cloud:
    refresh:
      refreshable: none
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

mybatis:
  #开启驼峰命名法
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  # xml地址
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: io.nuls.nulsswitch.entity   #自己的实体类地址
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  basePackage: io.nuls.nulsswitch.controller

management:
  endpoints:
    web:
      exposure:
        include: '*'
# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "
nuls:
  api:
    address: beta.api.nuls.io